service: serverless-hexagonal-go

frameworkVersion: '3'
configValidationMode: error

provider:
  name: aws
  runtime: go1.x

package:
  patterns:
    - '!./**'
    - ./bin/**

functions:
  get-entry:
    handler: bin/get-entry
    events:
      - httpApi:
          method: GET
          path: /posts/{slug}

  list-entries:
    handler: bin/list-entries
    events:
      - httpApi:
          path: /posts
          method: get
